### ISSUE TITLE
Error: Was unable to open the browser "puppeteer:no_sandbox" due to error.

### ISSUE THREAD

**Issue by wangjianshuo** [jdobosz/testcafe-browser-provider-puppeteer#12]
use runner
  .browsers(['puppeteer:no_sandbox'])

error:  { Error: Was unable to open the browser "puppeteer:no_sandbox" due to error.

Error: WebSocket is not open: readyState 3 (CLOSED)

**Comment by rodrigotolledo** [comment]
I'm also facing the same issue. 

I'm using `testcafe-browser-provider-puppeteer` `1.4.0`
And `testcafe` `1.5.0`

Here is the Stack Trace:

```
 >>> ERROR: GeneralError: Was unable to open the browser "puppeteer:" due to error.
 
 Error: WebSocket is not open: readyState 3 (CLOSED)
     at WebSocket.send (D:\a\r1\a\git-automated-tests\node_modules\ws\lib\websocket.js:314:19)
     at WebSocketTransport.send (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\WebSocketTransport.js:57:14)
     at Connection._rawSend (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\Connection.js:86:21)
     at Connection.send (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\Connection.js:72:21)
     at Browser._createPageInContext (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\Browser.js:174:47)
     at BrowserContext.newPage (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\Browser.js:360:26)
     at Browser.newPage (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\Browser.js:166:33)
     at Browser.<anonymous> (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\helper.js:111:23)
     at BrowserProviderPluginHost._callee$ (D:\a\r1\a\git-automated-tests\node_modules\testcafe-browser-provider-puppeteer\lib\index.js:56:35)
     at tryCatch (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
   -- ASYNC --
     at Browser.<anonymous> (D:\a\r1\a\git-automated-tests\node_modules\puppeteer\lib\helper.js:110:27)
     at BrowserProviderPluginHost._callee$ (D:\a\r1\a\git-automated-tests\node_modules\testcafe-browser-provider-puppeteer\lib\index.js:56:35)
     at tryCatch (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:45:40)
     at Generator.invoke [as _invoke] (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:271:22)
     at Generator.prototype.<computed> [as next] (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:97:21)
     at asyncGeneratorStep (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
     at _next (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
     at D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
     at new Promise (<anonymous>)
     at BrowserProviderPluginHost.<anonymous> (D:\a\r1\a\git-automated-tests\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
     at BrowserConnection._runBrowser (D:\a\r1\a\git-automated-tests\node_modules\testcafe\src\browser\connection\index.js:87:32) {
   code: 'E1038',
   data: [
     'puppeteer:',
     'Error: WebSocket is not open: readyState 3 (CLOSED)\n' +
       '    at WebSocket.send (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\ws\\lib\\websocket.js:314:19)\n' +
       '    at WebSocketTransport.send (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\WebSocketTransport.js:57:14)\n' +
       '    at Connection._rawSend (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\Connection.js:86:21)\n' +
       '    at Connection.send (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\Connection.js:72:21)\n' +
       '    at Browser._createPageInContext (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\Browser.js:174:47)\n' +
       '    at BrowserContext.newPage (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\Browser.js:360:26)\n' +
       '    at Browser.newPage (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\Browser.js:166:33)\n' +
       '    at Browser.<anonymous> (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\helper.js:111:23)\n' +
       '    at BrowserProviderPluginHost._callee$ (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\testcafe-browser-provider-puppeteer\\lib\\index.js:56:35)\n' +
       '    at tryCatch (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n' +
       '  -- ASYNC --\n' +
       '    at Browser.<anonymous> (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\puppeteer\\lib\\helper.js:110:27)\n' +
       '    at BrowserProviderPluginHost._callee$ (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\testcafe-browser-provider-puppeteer\\lib\\index.js:56:35)\n' +
       '    at tryCatch (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\node_modules\\regenerator-runtime\\runtime.js:45:40)\n' +
       '    at Generator.invoke [as _invoke] (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\node_modules\\regenerator-runtime\\runtime.js:271:22)\n' +
       '    at Generator.prototype.<computed> [as next] (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\node_modules\\regenerator-runtime\\runtime.js:97:21)\n' +
       '    at asyncGeneratorStep (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n' +
       '    at _next (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n' +
       '    at D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n' +
       '    at new Promise (<anonymous>)\n' +
       '    at BrowserProviderPluginHost.<anonymous> (D:\\a\\r1\\a\\git-automated-tests\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12)'
   ]
 }
 npm ERR! code ELIFECYCLE
 npm ERR! errno 1
 npm ERR! Exit status 1

```

@jdobosz, any idea or workaround?

Thank you!

**Comment by renita1509** [comment]
Also facing the same issue above as reported by Rodrigotolledo:

I'm using testcafe-browser-provider-puppeteer 1.4.0
And testcafe 1.7.0

Any suggestions to fix this or a workaround would be greatly appreciated.Thanks

**Comment by jdobosz** [comment]
just tested again the plugin 1.4.0 bound to chromium 78.0.3882 with testcafe 1.5.0 locally on linux and on jenkins CI. It worked as expected. The mentioned issue seems to be related to windows. Unfortunately i don't use windows any more.

**Comment by renita1509** [comment]
Hi , would also like to mention that this issue happens intermittently, say every 10/12 times after a successful run.  And as mentioned the details are:

testcafe-browser-provider-puppeteer 1.4.0
And testcafe 1.7.0

**Comment by jdobosz** [comment]
On which OS you are?

**Comment by rodrigotolledo** [comment]
@jdobosz: Windows 10

The issue occurs intermittently.

**Comment by wgeorgecrisan** [comment]
Same issue here with testcafe 1.8.2 and puppeteer run via bitbucket pipelines docker container.
The issue appears intermittently roughly 1 out of 5 attempts.
